export const data = [
	{
		albumId: 1,
		id: 1,
		title: "accusamus ",
		url: "https://via.placeholder.com/600/92c952",
		thumbnailUrl: "https://via.placeholder.com/150/92c952",
		verified: true,
	},
	{
		albumId: 1,
		id: 2,
		title: "reprehenderit est ",
		url: "https://via.placeholder.com/600/771796",
		thumbnailUrl: "https://via.placeholder.com/150/771796",
		verified: true,
	},
	{
		albumId: 1,
		id: 3,
		title: "officia porro ",
		url: "https://via.placeholder.com/600/24f355",
		thumbnailUrl: "https://via.placeholder.com/150/24f355",
		verified: true,
	},
	{
		albumId: 1,
		id: 4,
		title: "culpa odio",
		url: "https://via.placeholder.com/600/d32776",
		thumbnailUrl: "https://via.placeholder.com/150/d32776",
		verified: true,
	},
	{
		albumId: 1,
		id: 5,
		title: "natus nisi",
		url: "https://via.placeholder.com/600/f66b97",
		thumbnailUrl: "https://via.placeholder.com/150/f66b97",
		verified: false,
	},
	{
		albumId: 1,
		id: 6,
		title: "accusamus ea ",
		url: "https://via.placeholder.com/600/56a8c2",
		thumbnailUrl: "https://via.placeholder.com/150/56a8c2",
		verified: true,
	},
	{
		albumId: 1,
		id: 7,
		title: "officia delectus",
		url: "https://via.placeholder.com/600/b0f7cc",
		thumbnailUrl: "https://via.placeholder.com/150/b0f7cc",
		verified: true,
	},
	{
		albumId: 1,
		id: 8,
		title: "aut porro ",
		url: "https://via.placeholder.com/600/54176f",
		thumbnailUrl: "https://via.placeholder.com/150/54176f",
		verified: true,
	},
	{
		albumId: 1,
		id: 9,
		title: "qui eius qui",
		url: "https://via.placeholder.com/600/51aa97",
		thumbnailUrl: "https://via.placeholder.com/150/51aa97",
		verified: true,
	},
	{
		albumId: 1,
		id: 10,
		title: "beatae et provident",
		url: "https://via.placeholder.com/600/810b14",
		thumbnailUrl: "https://via.placeholder.com/150/810b14",
		verified: false,
	},
	{
		albumId: 1,
		id: 11,
		title: "nihil at amet",
		url: "https://via.placeholder.com/600/1ee8a4",
		thumbnailUrl: "https://via.placeholder.com/150/1ee8a4",
		verified: false,
	},
	{
		albumId: 1,
		id: 12,
		title: "mollitia soluta",
		url: "https://via.placeholder.com/600/66b7d2",
		thumbnailUrl: "https://via.placeholder.com/150/66b7d2",
		verified: false,
	},
	{
		albumId: 1,
		id: 13,
		title: "repudiandae iusto",
		url: "https://via.placeholder.com/600/197d29",
		thumbnailUrl: "https://via.placeholder.com/150/197d29",
		verified: false,
	},
	{
		albumId: 1,
		id: 14,
		title: "est necessitatibus",
		url: "https://via.placeholder.com/600/61a65",
		thumbnailUrl: "https://via.placeholder.com/150/61a65",
		verified: false,
	},
	{
		albumId: 1,
		id: 15,
		title: "harum dicta",
		url: "https://via.placeholder.com/600/f9cee5",
		thumbnailUrl: "https://via.placeholder.com/150/f9cee5",
		verified: false,
	},
	{
		albumId: 1,
		id: 16,
		title: "iusto sunt nobis",
		url: "https://via.placeholder.com/600/fdf73e",
		thumbnailUrl: "https://via.placeholder.com/150/fdf73e",
		verified: false,
	},
	{
		albumId: 1,
		id: 17,
		title: "natus doloribus",
		url: "https://via.placeholder.com/600/9c184f",
		thumbnailUrl: "https://via.placeholder.com/150/9c184f",
		verified: false,
	},
	{
		albumId: 1,
		id: 18,
		title: "laboriosam odit nam",
		url: "https://via.placeholder.com/600/1fe46f",
		thumbnailUrl: "https://via.placeholder.com/150/1fe46f",
		verified: false,
	},
	{
		albumId: 1,
		id: 19,
		title: "perferendis nesciun",
		url: "https://via.placeholder.com/600/56acb2",
		thumbnailUrl: "https://via.placeholder.com/150/56acb2",
		verified: false,
	},
	{
		albumId: 1,
		id: 20,
		title: "assumenda voluptatem",
		url: "https://via.placeholder.com/600/8985dc",
		thumbnailUrl: "https://via.placeholder.com/150/8985dc",
		verified: false,
	},
];
